31 submit button logic
Brute-Force-Programmers/brute-force-latin pull request #35
Opened 2022-03-01 01:20 UTC by rpupo7322

closes #31

2022-03-01 01:22 UTC, g-strick requested changes
CSS should not be in components folder. Please place in a stylesheet folder

2022-03-01 23:04 UTC, rpupo7322 commented
> CSS should not be in components folder. Please place in a stylesheet folder

The react documentation under "Grouping by file type" suggests putting the CSS in the components folder.
https://reactjs.org/docs/faq-structure.html

2022-03-21 17:16 UTC, g-strick approved these changes

2022-03-21 17:16 UTC, g-strick commented
LGTM

2022-03-21 17:16 UTC, closed without merging